name: Dockerize

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build container image
        run: make docker

      - name: Log in to the Container Registry with short-lived credentials
        run: docker login -u ${{ secrets.DOCKER_REGISTRY_LOGIN }} -p ${{ secrets.DOCKER_REGISTRY_PASSWD }} registry.marahin.pl

      - name: Push image to Container Registry
        run: make push-to-registry
